# Site settings
title: Véro + John
description: 'photos from 31.03.2018 by <a href="http://lemonteahk.com" target="_blank">LemonTeaHK</a>'
baseurl: "/gallery_tai_hang" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
title_link: "http://vero.et.johnho.ca/pages/tai_hang"
image_dir: "images/fulls/" #1200x750
image_tn_dir: "images/thumbs/"  #360x225

# Google Analytics
google_analytics_tracking_id: UA-113486763-2

# Footer data
footer_title: More + Download
footer_text: 'More pictures available by <a href="#">Mike Szeto</a>. <br/><br/><a href="http://files.johnho.ca/owncloud/index.php/s/Iw6p3e5t3CsiFV9">Download</a> these awesome pictures (Password: littletaihang).'
show_social: false
show_contact_form: false
credit_text: 'Created with  &hearts; by <a href="http://johnho.ca">JHO</a>.'

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/explore/tags/veroetjohn/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
